name: Lint JS

on:
  push:
    paths:
      - "_javascript/**/*.js"
      - ".github/workflows/scripts/**/*.js"
      - "*.js"
  pull_request:
    paths:
      - "_javascript/**/*.js"
      - ".github/workflows/scripts/*.js"
      - "*.js"

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint JS
        run: pnpm run lint:js
